defmodule WhisprNotifications.Repo.Migrations.ChangeNotificationHistoryIdToUuid do
  use Ecto.Migration

  @moduledoc """
  Converts `notification_history.id` (and `conversation_id`) from varchar to
  uuid to match the application schema (`@primary_key {:id, Ecto.UUID}`) and
  the reality of preprod (where the column already exists as `uuid`).

  WHISPR-1142: the original migration declared `:string` but preprod was
  apparently reconciled to `uuid` manually, which caused a permanent mismatch
  between test (varchar) and preprod (uuid). Make the migration the source of
  truth — test Postgres now also uses `uuid`, matching preprod.
  """

  def up do
    # `id` always contains a valid UUID (generated by Ecto.UUID.generate/0 in
    # Notifications.create/1), so an unconditional cast is safe.
    execute(
      "ALTER TABLE notification_history ALTER COLUMN id TYPE uuid USING id::uuid"
    )
  end

  def down do
    execute(
      "ALTER TABLE notification_history ALTER COLUMN id TYPE varchar(255) USING id::text"
    )
  end
end
